- name:  Setup laravel
  hosts: all
  vars:
    - become: yes
  vars_files:
    - vars/main.yaml
  
  roles:
    # - update-system
    # - package
    - mariadb
    # - update-system
    # - site-laravel
    # - apache2
    # - letsencrypt