---

- name: Set permission folder wwww
  ansible.builtin.file:
    path: /var/www/
    state: directory
    mode: '0775'
    recurse: yes
  become: "{{ become }}"

- name: Change ownership on wwww
  ansible.builtin.file:
    path: /var/www/
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu
  become: "{{ become }}"

- name: Download Composer installer
  ansible.builtin.get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer.php
  become: "{{ become }}"

- name: Run Composer installer
  ansible.builtin.shell: php /tmp/installer.php --install-dir=/usr/local/bin --filename=composer
  args:
    executable: /bin/bash
  become: "{{ become }}"

- name: Clone the Git Repository
  ansible.builtin.git:
    repo: "{{ Repo }}"
    dest: /var/www/{{ Domain }}
    clone: yes
    update: yes
    force: yes

- name: Run composer install
  ansible.builtin.command: composer update
  args:
   chdir: "/var/www/{{ Domain }}"

- name: Copy Env
  ansible.builtin.template:
    src:  ../templates/.env.example
    dest: /var/www/{{ Domain }}/.env

- name: Generate key
  ansible.builtin.command: php artisan key:generate
  args:
   chdir: "/var/www/{{ Domain }}"

- name: Change permission
  ansible.builtin.file:
    path: "/var/www/{{ Domain }}/storage"
    recurse: yes
    state: directory
    mode: 0777

# - name: Migrate db
#   ansible.builtin.command: php artisan migrate
#   args:
#    chdir: "/var/www/{{ Domain }}"
